export const VISAGISM_THINKING_PHRASES = [
  "Observando as linhas principais da armação...",
  "Identificando o formato predominante...",
  "Analisando a presença visual do modelo...",
  "Reconhecendo os detalhes de acabamento...",
  "Comparando proporções e contornos...",
  "Avaliando como a armação equilibra o rosto...",
  "Interpretando a linguagem visual do modelo...",
  "Mapeando os estilos que combinam com a peça...",
  "Analisando cor, material e personalidade...",
  "Organizando os atributos da armação...",
  "Refinando a leitura visagista...",
  "Identificando os perfis mais favorecidos...",
  "Avaliando a sensação transmitida pelo design...",
  "Reconhecendo os pontos de destaque da peça...",
  "Cruzando formato e percepção visual...",
  "Analisando a harmonia das proporções...",
  "Traduzindo o design em recomendações...",
  "Observando os detalhes que definem o estilo...",
  "Avaliando a estrutura frontal da armação...",
  "Identificando a assinatura estética do modelo...",
  "Relacionando a peça a diferentes formatos de rosto...",
  "Analisando o impacto visual da cor...",
  "Interpretando o acabamento e o material...",
  "Refinando as indicações de estilo...",
  "Buscando o melhor vocabulário para a recomendação...",
  "Organizando as características mais relevantes...",
  "Avaliando o equilíbrio entre leveza e presença...",
  "Reconhecendo os traços de personalidade da peça...",
  "Analisando como o modelo comunica confiança...",
  "Comparando linhas retas e curvas...",
  "Identificando o nível de contraste da armação...",
  "Avaliando a versatilidade do modelo...",
  "Relacionando design e expressão pessoal...",
  "Interpretando o estilo predominante...",
  "Mapeando as percepções que a peça transmite...",
  "Analisando a largura e a altura visual...",
  "Observando a espessura e o peso aparente...",
  "Avaliando a influência das hastes no conjunto...",
  "Reconhecendo detalhes clássicos e contemporâneos...",
  "Consolidando a análise da armação...",
  "Preparando uma descrição clara e consultiva...",
  "Refinando a recomendação para o atendimento...",
  "Organizando as melhores combinações de perfil...",
  "Avaliando a impressão causada à primeira vista...",
  "Identificando os contextos de uso mais naturais...",
  "Analisando o equilíbrio entre estilo e funcionalidade...",
  "Transformando características visuais em orientação...",
  "Revisando os atributos identificados pela IA...",
  "Conferindo a consistência da análise...",
  "Finalizando a descrição visagista do modelo...",
] as const;
