import { useCallback, useEffect, useRef, useState } from "react";
import { FolderPlus, ImageOff, ImagePlus, Loader2, RotateCcw, Tags, Trash2, X } from "lucide-react";
import { toast } from "sonner";

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import {
  analyzeAgentMedia, archiveAgentMedia, deleteAgentMediaCatalog, listAgentMediaCatalog, listArchivedAgentMedia, restoreAgentMedia,
  saveAgentMediaAsset, saveAgentMediaCatalog, type AgentMediaAsset, type AgentMediaCatalogState, type MediaCatalog,
} from "@/services/agentToolsService";

const inputClass = "h-10 w-full rounded-[var(--radius-md)] border border-[var(--border-input)] bg-[var(--color-surface-1)] px-3 text-sm shadow-inset focus-visible:outline-none focus-visible:shadow-focus";
const empty: AgentMediaCatalogState = { catalogs: [], assets: [], limit: 30, used: 0 };
type DraggedMedia = { asset: AgentMediaAsset; sourceCatalogId: string | null };

function remainingRetention(purgeAfter?: string | null) {
  if (!purgeAfter) return "Prazo de retenção indisponível";
  const days = Math.max(0, Math.ceil((new Date(purgeAfter).getTime() - Date.now()) / 86_400_000));
  return days === 1 ? "Expira em 1 dia" : `Expira em ${days} dias`;
}

function MediaThumbnail({ asset, sourceCatalogId, onSelect, onDragStart }: { asset: AgentMediaAsset; sourceCatalogId: string | null; onSelect: (asset: AgentMediaAsset) => void; onDragStart: (media: DraggedMedia) => void }) {
  const [previewFailed, setPreviewFailed] = useState(false);
  return <button type="button" draggable title={asset.title} onClick={() => onSelect(asset)} onDragStart={(event) => { event.dataTransfer.effectAllowed = "copyMove"; onDragStart({ asset, sourceCatalogId }); }} className="group block cursor-grab overflow-hidden rounded-[var(--radius-md)] border border-[var(--border-default)] bg-[var(--color-surface-1)] shadow-sm transition-[box-shadow,transform] hover:-translate-y-0.5 hover:shadow-md active:cursor-grabbing focus-visible:outline-none focus-visible:shadow-focus">
    <div className="aspect-square overflow-hidden bg-[var(--color-bg-muted)]">
      {asset.preview_url && !previewFailed ? <img src={asset.preview_url} alt={asset.title} onError={() => setPreviewFailed(true)} className="h-full w-full object-cover transition-transform duration-200 group-hover:scale-[1.02] motion-reduce:transition-none" /> : <div className="grid h-full place-items-center text-[var(--color-gray-400)]"><ImageOff className="h-5 w-5" /></div>}
    </div>
    <span className="sr-only">Editar {asset.title}</span>
  </button>;
}

function MediaGrid({ assets, sourceCatalogId, onSelect, onDragStart, onAdd }: { assets: AgentMediaAsset[]; sourceCatalogId: string | null; onSelect: (asset: AgentMediaAsset) => void; onDragStart: (media: DraggedMedia) => void; onAdd?: () => void }) {
  return <div className="grid grid-cols-3 gap-2 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6">{onAdd ? <button type="button" onClick={onAdd} className="grid aspect-square place-items-center rounded-[var(--radius-md)] border border-dashed border-[var(--color-primary-300)] bg-[var(--color-primary-50)] text-[var(--color-primary-600)] transition-colors hover:bg-[var(--color-primary-100)] focus-visible:outline-none focus-visible:shadow-focus" aria-label="Adicionar foto nesta categoria"><ImagePlus className="h-5 w-5" /></button> : null}{assets.map((asset) => <MediaThumbnail key={asset.id} asset={asset} sourceCatalogId={sourceCatalogId} onSelect={onSelect} onDragStart={onDragStart} />)}</div>;
}

export function SendMediaCatalogPanel({ agentId, onChanged }: { agentId: string; onChanged: () => void }) {
  const file = useRef<HTMLInputElement>(null);
  const [data, setData] = useState(empty); const [trash, setTrash] = useState<AgentMediaAsset[]>([]); const [loading, setLoading] = useState(true);
  const [draft, setDraft] = useState<(Omit<AgentMediaAsset, "id" | "catalog_ids" | "send_enabled" | "origin"> & { draftId: string }) | null>(null);
  const [catalogName, setCatalogName] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false);
  const [categoryDialogOpen, setCategoryDialogOpen] = useState(false); const [catalogToDelete, setCatalogToDelete] = useState<MediaCatalog | null>(null); const [editingAsset, setEditingAsset] = useState<AgentMediaAsset | null>(null); const [editCatalogIds, setEditCatalogIds] = useState<string[]>([]);
  const [dragged, setDragged] = useState<DraggedMedia | null>(null); const [dropCatalogId, setDropCatalogId] = useState<string | null>(null); const [pendingDrop, setPendingDrop] = useState<{ media: DraggedMedia; targetCatalogId: string } | null>(null);

  const reload = useCallback(async () => { setLoading(true); try { const [catalog, archived] = await Promise.all([listAgentMediaCatalog(agentId), listArchivedAgentMedia(agentId)]); setData(catalog); setTrash(archived.assets); } catch (error) { toast.error("Não foi possível carregar as mídias", { description: error instanceof Error ? error.message : undefined }); } finally { setLoading(false); } }, [agentId]);
  useEffect(() => { void reload(); }, [reload]);

  async function createCatalog() { const name = catalogName.trim(); if (!name) return; if (data.catalogs.some((catalog) => catalog.name.localeCompare(name, undefined, { sensitivity: "accent" }) === 0)) { toast.error("Esta categoria já existe", { description: "Escolha outro nome para criar uma nova categoria." }); return; } try { await saveAgentMediaCatalog(agentId, { name }); setCatalogName(""); setCategoryDialogOpen(false); await reload(); toast.success("Categoria criada"); } catch (error) { toast.error("Não foi possível criar a categoria", { description: error instanceof Error ? error.message : undefined }); } }
  async function deleteCatalog(catalog: MediaCatalog) { setBusy(true); try { await deleteAgentMediaCatalog(agentId, catalog.id); setCatalogToDelete(null); await reload(); onChanged(); toast.success("Categoria excluída", { description: "As fotos foram movidas para Sem categoria." }); } catch (error) { toast.error("Não foi possível excluir a categoria", { description: error instanceof Error ? error.message : undefined }); } finally { setBusy(false); } }
  function startImageUpload(catalogId?: string) { setSelected(catalogId ? [catalogId] : []); if (file.current) file.current.value = ""; file.current?.click(); }
  async function chooseImage(candidate: File | null) { if (!candidate) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(candidate.type) || candidate.size > 10 * 1024 * 1024) { toast.error("Use JPG, PNG ou WebP de até 10 MB."); return; } setBusy(true); try { const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(candidate); }); const response = await analyzeAgentMedia(agentId, { fileName: candidate.name, mimeType: candidate.type, base64 }); setDraft(response.draft); } catch (error) { toast.error("Não foi possível analisar a foto", { description: error instanceof Error ? error.message : undefined }); } finally { setBusy(false); } }
  async function saveAsset(asset: AgentMediaAsset, input: { title: string; description: string; searchTerms: string[]; catalogIds: string[] }) { await saveAgentMediaAsset(agentId, { id: asset.id, ...input, sendEnabled: true }); await reload(); onChanged(); }
  async function saveDraft() { if (!draft) return; setBusy(true); try { await saveAgentMediaAsset(agentId, { id: draft.draftId, title: draft.title, description: draft.description, searchTerms: draft.search_terms, catalogIds: selected, sendEnabled: true }); setDraft(null); setSelected([]); await reload(); onChanged(); toast.success("Foto adicionada ao catálogo"); } catch (error) { toast.error("Não foi possível salvar a foto", { description: error instanceof Error ? error.message : undefined }); } finally { setBusy(false); } }
  async function archive(asset: AgentMediaAsset) { setBusy(true); try { await archiveAgentMedia(agentId, asset.id); setEditingAsset(null); await reload(); onChanged(); toast.success("Foto movida para a lixeira"); } catch (error) { toast.error("Não foi possível excluir a foto", { description: error instanceof Error ? error.message : undefined }); } finally { setBusy(false); } }
  async function restore(asset: AgentMediaAsset) { setBusy(true); try { await restoreAgentMedia(agentId, asset.id); await reload(); onChanged(); toast.success("Foto restaurada"); } catch (error) { toast.error("Não foi possível restaurar a foto", { description: error instanceof Error ? error.message : undefined }); } finally { setBusy(false); } }
  function openEditor(asset: AgentMediaAsset) { setEditingAsset(asset); setEditCatalogIds(asset.catalog_ids); }
  async function applyDrop(choice: "move" | "copy", request = pendingDrop) { if (!request) return; const { media, targetCatalogId } = request; const catalogIds = choice === "copy" ? [...new Set([...media.asset.catalog_ids, targetCatalogId])] : [...new Set(media.asset.catalog_ids.filter((id) => id !== media.sourceCatalogId).concat(targetCatalogId))]; try { await saveAsset(media.asset, { title: media.asset.title, description: media.asset.description, searchTerms: media.asset.search_terms, catalogIds }); toast.success(choice === "move" ? "Foto movida" : "Foto adicionada à categoria"); } catch (error) { toast.error("Não foi possível atualizar a categoria", { description: error instanceof Error ? error.message : undefined }); } finally { setPendingDrop(null); } }
  function handleDrop(targetCatalogId: string) { const media = dragged; setDragged(null); setDropCatalogId(null); if (!media || media.sourceCatalogId === targetCatalogId || media.asset.catalog_ids.includes(targetCatalogId)) return; if (!media.sourceCatalogId) { void applyDrop("move", { media, targetCatalogId }); return; } setPendingDrop({ media, targetCatalogId }); }
  const uncategorizedAssets = data.assets.filter((asset) => asset.catalog_ids.length === 0);

  if (loading) return <div className="flex min-h-48 items-center justify-center text-sm text-[var(--color-gray-500)]"><Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none" />Carregando mídias</div>;

  return <section className="space-y-5 rounded-[var(--radius-xl)] border border-[var(--border-default)] bg-[var(--color-surface-1)] p-4 shadow-sm sm:p-5">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border-default)] pb-4"><p className="text-xs text-[var(--color-gray-600)]">{data.used} de {data.limit} fotos da empresa em uso. Fotos de Visagismo não entram na cota.</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setCategoryDialogOpen(true)}><FolderPlus /> Criar categoria</Button><Button onClick={() => startImageUpload()} disabled={busy || data.used >= data.limit}><ImagePlus /> Adicionar foto</Button></div><input ref={file} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void chooseImage(event.target.files?.[0] ?? null)} /></div>

    {draft ? <div className="space-y-4 rounded-[var(--radius-xl)] border border-[var(--color-primary-200)] p-4"><div className="flex justify-between gap-4"><div><h4 className="text-sm font-semibold">Revise a foto antes de adicionar</h4><p className="mt-1 text-xs text-[var(--color-gray-600)]">Escolha ao menos uma categoria para ativar o envio.</p></div><button type="button" onClick={() => setDraft(null)} className="p-1 text-[var(--color-gray-500)] focus-visible:shadow-focus"><X className="h-4 w-4" /></button></div><div className="grid gap-4 sm:grid-cols-[130px_1fr]"><div className="aspect-square overflow-hidden rounded-[var(--radius-lg)] bg-[var(--color-bg-muted)]">{draft.preview_url ? <img src={draft.preview_url} alt="Prévia" className="h-full w-full object-cover" /> : <ImageOff className="m-auto mt-12 h-5 w-5" />}</div><div className="grid gap-3"><label className="grid gap-1 text-xs font-semibold">Título<input className={inputClass} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label className="grid gap-1 text-xs font-semibold">Descrição<textarea className="min-h-20 rounded-[var(--radius-md)] border border-[var(--border-input)] p-3 text-sm shadow-inset focus-visible:shadow-focus" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label></div></div><div className="flex flex-wrap gap-2">{data.catalogs.map((catalog) => { const checked = selected.includes(catalog.id); return <label key={catalog.id} className="inline-flex items-center gap-2 rounded-[var(--radius-md)] border px-3 py-2 text-xs"><input type="checkbox" checked={checked} onChange={() => setSelected((ids) => checked ? ids.filter((id) => id !== catalog.id) : [...ids, catalog.id])} className="accent-[var(--color-primary-500)]" />{catalog.name}</label>; })}</div><div className="flex justify-end"><Button onClick={() => void saveDraft()} disabled={busy || !draft.title.trim() || selected.length === 0}>Salvar foto</Button></div></div> : null}

    {data.catalogs.length || uncategorizedAssets.length ? <Accordion type="multiple" className="overflow-hidden rounded-[var(--radius-xl)] border border-[var(--border-default)] bg-[var(--color-surface-1)] shadow-sm">{data.catalogs.map((catalog) => { const assets = data.assets.filter((asset) => asset.catalog_ids.includes(catalog.id)); const isDropTarget = dropCatalogId === catalog.id; return <AccordionItem key={catalog.id} value={catalog.id} className="border-[var(--border-default)] last:border-b-0" onDragOver={(event) => { event.preventDefault(); setDropCatalogId(catalog.id); }} onDragLeave={() => setDropCatalogId(null)} onDrop={() => handleDrop(catalog.id)}><AccordionTrigger className="px-4 py-3 text-left hover:no-underline focus-visible:shadow-focus"><span className="flex min-w-0 items-center gap-3"><Tags className="h-4 w-4 text-[var(--color-primary-500)]" /><span><strong className="block text-sm">{catalog.name}</strong><span className="text-xs font-normal text-[var(--color-gray-500)]">{assets.length} {assets.length === 1 ? "foto" : "fotos"}</span></span></span></AccordionTrigger><AccordionContent className="px-4"><div className={isDropTarget ? "rounded-[var(--radius-lg)] bg-[var(--color-primary-50)] p-2" : ""}><MediaGrid assets={assets} sourceCatalogId={catalog.id} onSelect={openEditor} onDragStart={setDragged} onAdd={() => startImageUpload(catalog.id)} /></div></AccordionContent></AccordionItem>; })}{uncategorizedAssets.length ? <AccordionItem value="uncategorized" className="border-[var(--border-default)]"><AccordionTrigger className="px-4 py-3 text-left hover:no-underline"><span className="flex items-center gap-3"><ImageOff className="h-4 w-4" /><span><strong className="block text-sm">Sem categoria</strong><span className="text-xs font-normal text-[var(--color-gray-500)]">{uncategorizedAssets.length} fotos</span></span></span></AccordionTrigger><AccordionContent className="px-4"><MediaGrid assets={uncategorizedAssets} sourceCatalogId={null} onSelect={openEditor} onDragStart={setDragged} /></AccordionContent></AccordionItem> : null}</Accordion> : <div className="rounded-[var(--radius-xl)] border border-dashed p-8 text-center text-sm text-[var(--color-gray-500)]">Crie uma categoria e adicione a primeira foto.</div>}

    <details className="rounded-[var(--radius-lg)] border border-[var(--border-default)]"><summary className="cursor-pointer px-4 py-3 text-sm font-medium text-[var(--color-gray-700)]">Lixeira {trash.length ? `(${trash.length})` : ""}</summary><div className="space-y-2 border-t p-3">{trash.length ? trash.map((asset) => <div key={asset.id} className="flex items-center justify-between gap-3 rounded-[var(--radius-md)] bg-[var(--color-bg-subtle)] px-3 py-2"><span className="min-w-0"><span className="block truncate text-sm">{asset.title}</span><span className="text-xs text-[var(--color-gray-500)]">{remainingRetention(asset.purge_after)}</span></span><Button size="sm" variant="outline" disabled={busy} onClick={() => void restore(asset)}><RotateCcw /> Restaurar</Button></div>) : <p className="text-xs text-[var(--color-gray-500)]">Nenhuma foto excluída.</p>}</div></details>

    <Dialog open={categoryDialogOpen} onOpenChange={setCategoryDialogOpen}><DialogContent><DialogHeader><DialogTitle>Gerenciar categorias</DialogTitle><DialogDescription>Crie categorias e organize o catálogo. Excluir uma categoria não exclui as fotos.</DialogDescription></DialogHeader><form className="grid gap-3" onSubmit={(event) => { event.preventDefault(); void createCatalog(); }}><label className="grid gap-1 text-xs font-semibold">Nova categoria<input autoFocus className={inputClass} value={catalogName} onChange={(event) => setCatalogName(event.target.value)} placeholder="Ex.: Voucher" /></label><Button type="submit" className="justify-self-end" disabled={!catalogName.trim() || busy}><FolderPlus /> Criar categoria</Button></form><div className="max-h-60 space-y-2 overflow-y-auto border-t pt-4">{data.catalogs.length ? data.catalogs.map((catalog) => { const count = data.assets.filter((asset) => asset.catalog_ids.includes(catalog.id)).length; return <div key={catalog.id} className="flex items-center justify-between gap-3 rounded-[var(--radius-md)] border border-[var(--border-default)] px-3 py-2"><span className="min-w-0"><span className="block truncate text-sm font-medium">{catalog.name}</span><span className="text-xs text-[var(--color-gray-500)]">{count} {count === 1 ? "foto" : "fotos"}</span></span><Button type="button" size="icon" variant="ghost" className="shrink-0 text-[var(--color-error-600)] hover:bg-[var(--color-error-50)] hover:text-[var(--color-error-700)]" onClick={() => setCatalogToDelete(catalog)} aria-label={`Excluir categoria ${catalog.name}`}><Trash2 /></Button></div>; }) : <p className="py-3 text-center text-sm text-[var(--color-gray-500)]">Nenhuma categoria criada.</p>}</div><DialogFooter><Button type="button" variant="outline" onClick={() => setCategoryDialogOpen(false)}>Concluir</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(catalogToDelete)} onOpenChange={(open) => { if (!open) setCatalogToDelete(null); }}><DialogContent><DialogHeader><DialogTitle>Excluir categoria?</DialogTitle><DialogDescription>{catalogToDelete ? `“${catalogToDelete.name}” será excluída. As fotos vinculadas continuarão no catálogo, em Sem categoria.` : ""}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setCatalogToDelete(null)} disabled={busy}>Cancelar</Button><Button variant="destructive" onClick={() => { if (catalogToDelete) void deleteCatalog(catalogToDelete); }} disabled={busy}><Trash2 /> Excluir categoria</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(editingAsset)} onOpenChange={(open) => { if (!open) setEditingAsset(null); }}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Editar foto</DialogTitle><DialogDescription>Revise as informações usadas pelo agente.</DialogDescription></DialogHeader>{editingAsset ? <form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void saveAsset(editingAsset, { title: String(form.get("title") ?? ""), description: String(form.get("description") ?? ""), searchTerms: String(form.get("terms") ?? "").split(",").map((item) => item.trim()).filter(Boolean), catalogIds: editCatalogIds }).then(() => { setEditingAsset(null); toast.success("Foto atualizada"); }).catch((error) => toast.error("Não foi possível salvar", { description: error instanceof Error ? error.message : undefined })); }}><div className="grid gap-4 sm:grid-cols-[112px_1fr]"><div className="aspect-square overflow-hidden rounded-[var(--radius-lg)] bg-[var(--color-bg-muted)]">{editingAsset.preview_url ? <img src={editingAsset.preview_url} alt={editingAsset.title} className="h-full w-full object-cover" /> : <ImageOff className="m-auto mt-10 h-5 w-5" />}</div><div className="grid gap-3"><label className="grid gap-1 text-xs font-semibold">Título<input name="title" defaultValue={editingAsset.title} required className={inputClass} /></label><label className="grid gap-1 text-xs font-semibold">Termos de busca<input name="terms" defaultValue={editingAsset.search_terms.join(", ")} className={inputClass} /></label></div></div><label className="grid gap-1 text-xs font-semibold">Descrição<textarea name="description" defaultValue={editingAsset.description} className="min-h-24 rounded-[var(--radius-md)] border border-[var(--border-input)] p-3 text-sm shadow-inset" /></label><div className="flex flex-wrap gap-2">{data.catalogs.map((catalog) => { const checked = editCatalogIds.includes(catalog.id); return <label key={catalog.id} className="inline-flex items-center gap-2 rounded-[var(--radius-md)] border px-3 py-2 text-xs"><input type="checkbox" checked={checked} onChange={() => setEditCatalogIds((ids) => checked ? ids.filter((id) => id !== catalog.id) : [...ids, catalog.id])} />{catalog.name}</label>; })}</div><DialogFooter className="gap-2"><Button type="button" variant="outline" onClick={() => void archive(editingAsset)} disabled={busy} className="border-[var(--color-error-300)] text-[var(--color-error-600)]"><Trash2 /> Excluir</Button><Button type="submit" disabled={busy || editCatalogIds.length === 0}>Salvar alterações</Button></DialogFooter></form> : null}</DialogContent></Dialog>
    <Dialog open={Boolean(pendingDrop)} onOpenChange={(open) => { if (!open) setPendingDrop(null); }}><DialogContent><DialogHeader><DialogTitle>Organizar foto</DialogTitle><DialogDescription>Deseja mover a foto ou utilizá-la também nesta categoria?</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setPendingDrop(null)}>Cancelar</Button><Button variant="outline" onClick={() => void applyDrop("copy")}>Usar também</Button><Button onClick={() => void applyDrop("move")}>Mover</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}
