#!/usr/bin/env bash

set -Eeuo pipefail
umask 077

ENV_FILE="${1:-.env.local}"
TTS_ENABLED="${ELEVENLABS_TTS_ENABLED_DEFAULT:-false}"
BI_ENABLED="${BI_PROJECTION_WORKER_ENABLED_DEFAULT:-true}"
VISAGISM_ENABLED="${VISAGISM_TOOL_ENABLED_DEFAULT:-false}"

if [[ "$TTS_ENABLED" != "true" && "$TTS_ENABLED" != "false" ]]; then
  printf 'ELEVENLABS_TTS_ENABLED_DEFAULT deve ser true ou false.\n' >&2
  exit 1
fi

if [[ "$BI_ENABLED" != "true" && "$BI_ENABLED" != "false" ]]; then
  printf 'BI_PROJECTION_WORKER_ENABLED_DEFAULT deve ser true ou false.\n' >&2
  exit 1
fi

if [[ "$VISAGISM_ENABLED" != "true" && "$VISAGISM_ENABLED" != "false" ]]; then
  printf 'VISAGISM_TOOL_ENABLED_DEFAULT deve ser true ou false.\n' >&2
  exit 1
fi

mkdir -p "$(dirname -- "$ENV_FILE")"
touch "$ENV_FILE"
TEMP_FILE="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
trap 'rm -f -- "$TEMP_FILE"' EXIT

grep -Ev '^(ELEVENLABS_TTS_ENABLED|ELEVENLABS_DEFAULT_VOICE_ID|ELEVENLABS_TTS_MODEL|ELEVENLABS_OUTPUT_FORMAT|TOOL_MEDIA_ALLOWED_HOSTS|VISAGISM_TOOL_ENABLED|VISAGISM_INTERNAL_RUNTIME_ENABLED|VISAGISM_ANALYSIS_WORKER_MODEL|VISAGISM_MATCHING_WORKER_MODEL|VISAGISM_IMAGE_WORKER_MODEL|PRESCRIPTION_WORKER_ENABLED|PRESCRIPTION_WORKER_MODEL|BI_PROJECTION_WORKER_ENABLED|BI_PROJECTION_BATCH_SIZE|BACKEND_UPDATE_ORDER)=' \
  "$ENV_FILE" > "$TEMP_FILE" || true

cat >> "$TEMP_FILE" <<EOF
ELEVENLABS_TTS_ENABLED=${TTS_ENABLED}
ELEVENLABS_DEFAULT_VOICE_ID=
ELEVENLABS_TTS_MODEL=eleven_flash_v2_5
ELEVENLABS_OUTPUT_FORMAT=mp3_44100_128
TOOL_MEDIA_ALLOWED_HOSTS=
VISAGISM_TOOL_ENABLED=${VISAGISM_ENABLED}
VISAGISM_INTERNAL_RUNTIME_ENABLED=true
VISAGISM_ANALYSIS_WORKER_MODEL=gemini-2.5-flash
VISAGISM_MATCHING_WORKER_MODEL=gemini-2.5-flash
VISAGISM_IMAGE_WORKER_MODEL=gpt-image-1
PRESCRIPTION_WORKER_ENABLED=true
PRESCRIPTION_WORKER_MODEL=gemini-2.5-flash
BI_PROJECTION_WORKER_ENABLED=${BI_ENABLED}
BI_PROJECTION_BATCH_SIZE=100
BACKEND_UPDATE_ORDER=stop-first
EOF

mv -f -- "$TEMP_FILE" "$ENV_FILE"
trap - EXIT
printf 'Defaults do backend de oticas configurados sem exibir segredos.\n'
